### ISSUE TITLE
New setup config cannot find module

### ISSUE THREAD

**Issue by AlexHls** [artis-mcrt/artistools#43]
Using `python=3.10.9` and `setuptools=65.5.0`, the latest change to the setup procedure (https://github.com/artis-mcrt/artistools/commit/63564c725ed0aed5dd5ff05a1e81448de00a12fd) leads to a `ModuleNotFoundError: No module named 'artistools'` error. (Tested both with a conda and venv environment, following the installation instructions)

Reverting the changes resolves this issue. If this commit was done with certain python/setuptools/package versions in mind, then these should be added to the requirements/ installation instructions.

**Comment by lukeshingles** [comment]
Hi, there's no strong justification for the change change, so let's revert to what works. The commit was just me trying to figure out how modern Python packages should be specified (with pyproject.toml) while avoiding deprecated methods.
